name: caption_trans
description: "Video subtitle extraction and translation app using Whisper and LLM."
publish_to: 'none'
version: 1.1.2+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Whisper / Audio
  ffmpeg_kit_flutter_new_min: ^3.1.0
  ffmpeg_kit_extended_flutter:
    git:
      url: https://github.com/cddqssc/ffmpeg-kit-extended.git
      path: flutter

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Utilities
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  package_info_plus: ^9.0.0
  path: ^1.9.0
  share_plus: ^12.0.1
  crypto: ^3.0.6
  archive: ^4.0.7
  url_launcher: ^6.3.2

  # Networking & Storage
  http: ^1.6.0
  shared_preferences: ^2.3.0

  # UI
  cupertino_icons: ^1.0.8

  universal_io: ^2.3.1
  uuid: ^4.5.3

ffmpeg_kit_extended_config:
  linux: "https://github.com/akashskypatel/ffmpeg-kit-builders/releases/download/v0.8.2-linux/bundle-base-linux-x86_64-shared-small-gpl.zip"
  windows: "https://github.com/akashskypatel/ffmpeg-kit-builders/releases/download/v0.8.2-windows/bundle-base-windows-x86_64-shared-small-gpl.zip"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

#dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  macos:
    generate: true
  windows:
    generate: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sidecar/
